title: Predictive Analytics for Student Success
description: VLE-based early-warning analytics for student retention.

# Pick ONE theme and leave that line uncommented.

theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman
# theme: jekyll-theme-slate
# theme: jekyll-theme-midnight
# theme: jekyll-theme-modernist
# theme: jekyll-theme-merlot
# theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine
